// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64
// +build 386 amd64 amd64p32 arm arm64 mips64le mips64p32le mipsle ppc64le riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfArgKey struct {
	Pid  uint32
	Tgid uint32
}

type bpfArgVal struct{ ArgsArray [10][20]int8 }

type bpfBufsT struct{ Buf [32768]uint8 }

type bpfMapkey struct {
	Pid   uint32
	Mntid uint32
	Path  [255]int8
	_     [1]byte
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	EnforceBprm  *ebpf.ProgramSpec `ebpf:"enforce_bprm"`
	KprobeExecve *ebpf.ProgramSpec `ebpf:"kprobe__execve"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ArgsMap    *ebpf.MapSpec `ebpf:"args_map"`
	Bufs       *ebpf.MapSpec `ebpf:"bufs"`
	BufsOffset *ebpf.MapSpec `ebpf:"bufs_offset"`
	CountMap   *ebpf.MapSpec `ebpf:"count_map"`
	Events     *ebpf.MapSpec `ebpf:"events"`
	PathMap    *ebpf.MapSpec `ebpf:"path_map"`
	Values     *ebpf.MapSpec `ebpf:"values"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ArgsMap    *ebpf.Map `ebpf:"args_map"`
	Bufs       *ebpf.Map `ebpf:"bufs"`
	BufsOffset *ebpf.Map `ebpf:"bufs_offset"`
	CountMap   *ebpf.Map `ebpf:"count_map"`
	Events     *ebpf.Map `ebpf:"events"`
	PathMap    *ebpf.Map `ebpf:"path_map"`
	Values     *ebpf.Map `ebpf:"values"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ArgsMap,
		m.Bufs,
		m.BufsOffset,
		m.CountMap,
		m.Events,
		m.PathMap,
		m.Values,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	EnforceBprm  *ebpf.Program `ebpf:"enforce_bprm"`
	KprobeExecve *ebpf.Program `ebpf:"kprobe__execve"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.EnforceBprm,
		p.KprobeExecve,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
